### ISSUE TITLE
회원가입 에이전트로 선택하고 하면 에러

### ISSUE THREAD

**Issue by heejeongMin** [heejeongMin/sabangSpring#13]
회원가입시 라디오버튼에서 에이전트 선택하고 회원가입진행하면 에러남

--- 에러 -- 

Type Status Report

Message /sabang/WEB-INF/views/signMbr.jsp

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

**Comment by HJGHM** [comment]
멤버타입을 선택하는 라디오버튼이 form 태그 바깥에 선언되어있어 컨트롤러로 값을 전달하지 못하였음.

현재 form태그 내부로 이동하여 값 전달 가능, 에이전트로 회원가입에 성공.
