### ISSUE TITLE
메인화면에서 houseoverview로 넘어갈 때 최근본방 정보가 없으면 에러가 발생

### ISSUE THREAD

**Issue by pts4779** [heejeongMin/sabangSpring#14]
메인화면에서 overview화면을 요청할 때 최근에 업로드한 방에 정보가 없으면 null을 받아 예외가 발생함. 최근에 업로드한 방에 대한 정보가 없어도 정상적으로 화면처리가 되도록 예외처리가 필요함.

3월 24, 2019 11:26:00 오전 org.apache.catalina.core.StandardWrapperValve invoke
심각: Servlet.service() for servlet [appServlet] in context with path [/sabang] threw exception [Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='maxSeven', mode=IN, javaType=class java.lang.String, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #1 with JdbcType OTHER . Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: 부적합한 열 유형: 1111] with root cause
java.sql.SQLException: 부적합한 열 유형: 1111

**Comment by heejeongMin** [comment]
### 기존 문제점
**신매물리스트를 불러오는 기준이되는 maxSeven 변수에 값을 넣어주는 HouseMapper.newItemCount 쿼리에서 null 값이 나오는경우 그 다음 실행되는 쿼리인 HouseMapper.retrieveNewItems 에서 실행하다가  null pointer exception 발생** 

_문제 코드1 - HouseDAO_
```
public List<HashMap<String, Object>> retrieveNewItems() {
     String maxSeven = session.selectOne("HouseMapper.newItemCount");
     return session.selectList("HouseMapper.retrieveNewItems", maxSeven);
}
```

_문제 코드2 - HouseMapper_
```
<select id="retrieveNewItems" parameterType="string" resultType="hashmap">
	select hcode, htype, rtype, hname, area, coordx, coordy, flr, hetc, himage, deposit, mrent, yrent, maintc
	from house_info join house_price using(hcode)
	where registerdate >= #{maxSeven}
</select>

<select id="newItemCount" resultType="string">
    	select to_char(max(registerdate)-7, 'yyyymmdd') from house_info
</select>
```

### 해결방법 
**DAO에서 처음 실행되는 쿼리의 결과값인 maxSeven이 null인지를 체크하고 null이면 Calendar에서 오늘 날짜를 만들어서 두번째쿼리의 파라미터로 보냄.** 
_수정 코드 - HouseDAO_
```
public List<HashMap<String, Object>> retrieveNewItems() {
	String maxSeven = session.selectOne("HouseMapper.newItemCount");
	if (maxSeven == null) {
		Calendar today = Calendar.getInstance();
		String year = String.valueOf(today.get(Calendar.YEAR));
		String month = (today.get(Calendar.MONTH) < 10)? "0"+(today.get(Calendar.MONTH)+1) : String.valueOf(today.get(Calendar.MONTH)+1);
		String date = (today.get(Calendar.DATE) <10)? "0"+today.get(Calendar.DATE) : String.valueOf(today.get(Calendar.DATE));
			
		maxSeven = year+month+date;
	}
		
	return session.selectList("HouseMapper.retrieveNewItems", maxSeven);`
}
```
