### ISSUE TITLE
회원가입 - 주민번호/전화번호 유효성 체크 

### ISSUE THREAD

**Issue by heejeongMin** [heejeongMin/sabangSpring#3]
현재 회원가입할때 주민번호, 전화번호 중복되는 데이터가 DB에 있으면 브라우저에 error화면이 보여짐. 유효성 체크 필요.

**Comment by HJGHM** [comment]
ID,주민번호, 핸드폰번호 즉 유니크 데이터를 ajax로 유효성 검사 처리했으며, 
중복 데이터를 입력하고 submit을 시도할 시 event.preventDefault로 submit을 방지하고 
alert로 수정을 요구하도록 변경.
